export const mockMainTable = [
  // {
  //   id: 1,
  //   alert: '🔴',
  //   status: 'Needs Review',
  //   poNumber: '33308',
  //   job: 'Magnolia Phase 6 Lots 39-45',
  //   phaseLots: 'Magnolia Phase 6 Lots 39-45',
  //   vendor: 'Woodgrain Millwork',
  //   requiredDate: '06/11/2026',
  //   vendorShipDate: '06/05/2026',
  //   total: '$24,658.72',
  //   issues: '4',
  //   confirmation: 'Received'
  // },
  // {
  //   id: 2,
  //   alert: '⚠️',
  //   status: 'Awaiting Confirmation',
  //   poNumber: '33307',
  //   job: 'Magnolia Phase 6 Lots 33-38',
  //   phaseLots: 'Magnolia Phase 6 Lots 33-38',
  //   vendor: 'Metrie EL & EL',
  //   requiredDate: '06/09/2026',
  //   vendorShipDate: '—',
  //   total: '$18,247.15',
  //   issues: '0',
  //   confirmation: 'Not Received'
  // },
  // {
  //   id: 3,
  //   alert: '🟢',
  //   status: 'PO Created',
  //   poNumber: '33306',
  //   job: 'Riverbend Apartments',
  //   phaseLots: 'Riverbend Apartments',
  //   vendor: 'Pamex Inc.',
  //   requiredDate: '06/05/2026',
  //   vendorShipDate: '06/03/2026',
  //   total: '$7,983.20',
  //   issues: '0',
  //   confirmation: 'Received'
  // },
  // {
  //   id: 4,
  //   alert: '🔴',
  //   status: 'Issues',
  //   poNumber: '33305',
  //   job: 'Magnolia Phase 5 Lots 21-32',
  //   phaseLots: 'Magnolia Phase 5 Lots 21-32',
  //   vendor: 'GH Hollow Metal Doors',
  //   requiredDate: '06/04/2026',
  //   vendorShipDate: '05/28/2026',
  //   total: '$31,456.80',
  //   issues: '3',
  //   confirmation: 'Received'
  // },
  // {
  //   id: 5,
  //   alert: '🟢',
  //   status: 'Closed',
  //   poNumber: '33304',
  //   job: 'Magnolia Phase 6 Lots 46-50',
  //   phaseLots: 'Magnolia Phase 6 Lots 46-50',
  //   vendor: 'ABS Doors',
  //   requiredDate: '06/12/2026',
  //   vendorShipDate: '06/08/2026',
  //   total: '$12,340.00',
  //   issues: '0',
  //   confirmation: 'Approved'
  // },
  // {
  //   id: 6,
  //   alert: '🟢',
  //   status: 'Approved',
  //   poNumber: '33303',
  //   job: 'The Heights Condo',
  //   phaseLots: 'The Heights Condo',
  //   vendor: 'Kohler',
  //   requiredDate: '05/30/2026',
  //   vendorShipDate: '06/01/2026',
  //   total: '$5,678.15',
  //   issues: '0',
  //   confirmation: 'Approved'
  // },
  // {
  //   id: 7,
  //   alert: '⚠️',
  //   status: 'Backordered',
  //   poNumber: '33302',
  //   job: 'Magnolia Phase 6 Lots 29-45',
  //   phaseLots: 'Magnolia Phase 6 Lots 29-45',
  //   vendor: 'DCI Hollow Metal',
  //   requiredDate: '06/02/2026',
  //   vendorShipDate: '07/10/2026',
  //   total: '$28,115.40',
  //   issues: '2',
  //   confirmation: 'Received'
  // },
  // {
  //   id: 8,
  //   alert: '🟢',
  //   status: 'Closed',
  //   poNumber: '33301',
  //   job: 'Magnolia Phase 4',
  //   phaseLots: 'Magnolia Phase 4',
  //   vendor: 'Liberty Glass',
  //   requiredDate: '05/15/2026',
  //   vendorShipDate: '05/12/2026',
  //   total: '$6,442.30',
  //   issues: '0',
  //   confirmation: 'Approved'
  // },
  // {
  //   id: 9,
  //   alert: '⚪',
  //   status: 'Draft',
  //   poNumber: '33300',
  //   job: 'Magnolia Phase 6 Lots 51-60',
  //   phaseLots: 'Magnolia Phase 6 Lots 51-60',
  //   vendor: 'Top Notch Hardware',
  //   requiredDate: '06/18/2026',
  //   vendorShipDate: '—',
  //   total: '$3,221.75',
  //   issues: '0',
  //   confirmation: 'Not Received'
  // },
  // {
  //   id: 10,
  //   alert: '🟡',
  //   status: 'Pending Approval',
  //   poNumber: '33299',
  //   job: 'Riverbend Apartments',
  //   phaseLots: 'Riverbend Apartments',
  //   vendor: 'Air Louvers',
  //   requiredDate: '06/08/2026',
  //   vendorShipDate: '—',
  //   total: '$4,560.00',
  //   issues: '0',
  //   confirmation: 'Not Received'
  // },
  // {
  //   id: 11,
  //   alert: '🟣',
  //   status: 'Awaiting Confirmation',
  //   poNumber: '33298',
  //   job: 'Oakridge Villas',
  //   phaseLots: 'Oakridge Villas Buildings A-C',
  //   vendor: 'Allegion',
  //   requiredDate: '06/14/2026',
  //   vendorShipDate: '—',
  //   total: '$9,845.00',
  //   issues: '1',
  //   confirmation: 'Not Received'
  // },
  // {
  //   id: 12,
  //   alert: '🔴',
  //   status: 'Needs Review',
  //   poNumber: '33297',
  //   job: 'Silver Creek Homes',
  //   phaseLots: 'Lots 12-19',
  //   vendor: 'Masonite',
  //   requiredDate: '06/06/2026',
  //   vendorShipDate: '06/01/2026',
  //   total: '$14,220.45',
  //   issues: '5',
  //   confirmation: 'Received'
  // },
  // {
  //   id: 14,
  //   alert: '🟢',
  //   status: 'Approved',
  //   poNumber: '33295',
  //   job: 'Parklane Residences',
  //   phaseLots: 'Tower 2',
  //   vendor: 'Schlage',
  //   requiredDate: '06/10/2026',
  //   vendorShipDate: '06/07/2026',
  //   total: '$16,770.60',
  //   issues: '0',
  //   confirmation: 'Approved'
  // }
  
];